n_sols: 
  value: 7
  min: 3
  max: 12

tabu_limit: 
  value: 15
  min: None
  max: None

pareto_limit:
  value: 15
  min: None
  max: None

max_tweak:
  value: 0.75
  min: 0.1
  max: 1

solution_comparison_alpha: 5e-2