#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS MODIFIED AUTOMATICALLY FROM TEMPLATE AND SHOULD BE RUNNABLE!
#SBATCH --partition=short
#SBATCH --job-name=testbed-small
#SBATCH --time=2:00:00
#SBATCH --output=/home/adeyemi.n/MH_Simulation/Inpatient_Bed_Allocation_Optimization/logs/testbed-small_%j.log
#SBATCH --error=/home/adeyemi.n/MH_Simulation/Inpatient_Bed_Allocation_Optimization/logs/error-files/testbed-small_%j.err

#SBATCH --mem=1G
#SBATCH --nodes=1
#SBATCH --gpus-per-task=0
#SBATCH --cpus-per-task=16

# Load modules or your own conda environment here
cd /home/adeyemi.n/MH_Simulation/Inpatient_Bed_Allocation_Optimization
source .bashrc
# ===== Call your code below =====
srun --unbuffered ~/.conda/envs/SMAC/bin/python Code/__main__.py --backend=dask --num-workers=1 --exp-name=testbed-small --yaml-path=configs/experiments.yaml --cluster-config=test 

exit 0