ed_ip_sim/mh_distance_range-mh_total_throughput:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_total_throughput-mh_distance_range
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_distance_range: &id001
      direction: '-'
    mh_total_throughput: &id002
      direction: +
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
ed_ip_sim/mh_wait_quantile-mh_distance_range:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_wait_quantile-mh_distance_range
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_distance_range: *id001
    mh_wait_quantile: &id003
      direction: '-'
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
ed_ip_sim/mh_wait_quantile-mh_distance_range-mh_total_throughput:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_wait_quantile-mh_distance_range-mh_total_throughput
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_distance_range: *id001
    mh_total_throughput: *id002
    mh_wait_quantile: *id003
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
ed_ip_sim/mh_wait_quantile-mh_total_throughput:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_wait_quantile-mh_total_throughput
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_total_throughput: *id002
    mh_wait_quantile: *id003
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
ed_ip_sim/mh_wait_quantile-mh_wait_sigma:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_wait_sigma-mh_wait_quantile
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_wait_quantile: *id003
    mh_wait_sigma: &id004
      direction: '-'
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
ed_ip_sim/mh_wait_quantile-mh_wait_sigma-mh_distance_range:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_wait_sigma-mh_wait_quantile-mh_distance_range
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_distance_range: *id001
    mh_wait_quantile: *id003
    mh_wait_sigma: *id004
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
ed_ip_sim/mh_wait_quantile-mh_wait_sigma-mh_distance_range-mh_total_throughput:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_wait_sigma-mh_wait_quantile-mh_distance_range-mh_total_throughput
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_distance_range: *id001
    mh_total_throughput: *id002
    mh_wait_quantile: *id003
    mh_wait_sigma: *id004
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
ed_ip_sim/mh_wait_quantile-mh_wait_sigma-mh_total_throughput:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_wait_sigma-mh_wait_quantile-mh_total_throughput
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_total_throughput: *id002
    mh_wait_quantile: *id003
    mh_wait_sigma: *id004
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
ed_ip_sim/mh_wait_sigma-mh_distance_range:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_wait_sigma-mh_distance_range
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_distance_range: *id001
    mh_wait_sigma: *id004
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
ed_ip_sim/mh_wait_sigma-mh_distance_range-mh_total_throughput:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_wait_sigma-mh_distance_range-mh_total_throughput
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_distance_range: *id001
    mh_total_throughput: *id002
    mh_wait_sigma: *id004
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
ed_ip_sim/mh_wait_sigma-mh_total_throughput:
  checkpoint-interval: 1
  cooling_schedule: quadratic
  hyper_params: default
  job_dir: experiments/ed_ip_sim/mh_wait_sigma-mh_total_throughput
  mo_ocba: default
  n_sols: 10
  obj_fns:
    mh_total_throughput: *id002
    mh_wait_sigma: *id004
  report_progress_interval: 5
  seed: 42
  stoch_optim: true
  termination_criteria:
    criteria_1:
      condition: '>'
      name: current_iteration
      value: 200
    criteria_2:
      condition: <
      name: temp
      value: 0.001
    criteria_3:
      condition: '>'
      name: pareto_set.counter
      value: 10
  tune: false
